main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('biodata', views.biodata, name='biodata'),
    path('ori', views.ori, name='ori'),
    path('matkul/', views.matkul, name="matkul"),
    path('detail_matkul/', views.list_matkul, name="list_matkul"),
    path('detail_matkul/<int:my_id>/',views.detail_matkul, name="detail_matkul"),
    path('detail_matkul/<int:my_id>/delete/', views.delete_matkul, name="detail_matkul_delete"),
    path('kegiatan/', views.kegiatan, name="kegiatan"),
    path('buku/', views.buku, name="buku"),
    path('initial/', views.initial, name="inital"),
    path('data/', views.data, name="data"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logOut, name="logout"),
    path('login/', views.logIn, name='login')
]

story_empat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.urls import reverse

# Create your models here.

class MataKuliah(models.Model):

    nama = models.CharField(max_length=20)
    dosen = models.CharField(max_length=20)
    sks = models.IntegerField()
    deskripsi = models.TextField()
    semester_tahun = models.CharField(max_length=20)
    ruang_kelas = models.CharField(max_length=20)

    def get_absolute_url(self):
        return f"/detail_matkul/{self.id}/"

class Kegiatan(models.Model):
    nama = models.CharField(max_length=30)

class Peserta(models.Model):
    nama = models.CharField(max_length=30)
    kegiatan = ForeignKey(Kegiatan, on_delete=models.CASCADE, default=None)

main/forms.py
from django import forms
from .models import MataKuliah
from django.contrib.auth.models import User

class MatkulForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = [
            'nama',
            'dosen',
            'sks',
            'deskripsi',
            'semester_tahun',
            'ruang_kelas'
        ]

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'email',
            'first_name',
            'last_name'
        ]

class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password',
        ]

main/views.py
from django.contrib import auth
from django.http import response, JsonResponse
from django.shortcuts import render, redirect

from .forms import MatkulForm, UserForm, SignUpForm
from .models import MataKuliah, Peserta
import requests, random
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

def home(request):
    return render(request, 'main/home.html')

def biodata(request):
    return render(request, 'main/biodata.html')

def ori(request):
    return render(request, 'main/ori.html')

def matkul(request):
    form = MatkulForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('/detail_matkul/')
    context = {
        'form' : form,
    }
    return render(request, "main/matkul.html", context)

def list_matkul(request):
    matkuls = MataKuliah.objects.all()
    context = {
        'matkuls' : matkuls
    }
    return render(request, "main/list_matkul.html", context)


def detail_matkul(request, my_id):
    matkul = MataKuliah.objects.get(id = my_id)
    context = {
        'matkul' : matkul
    }
    return render(request, "main/detail_matkul.html", context)

def delete_matkul(request, my_id):
    matkul = MataKuliah.objects.get(id = my_id)
    if request.method == "POST":
        matkul.delete()
        return redirect('../../')
    context={
        'matkul' : matkul
    }
    return render(request, "main/delete_matkul.html", context)

def kegiatan(request):
    response = {}
    return render(request, "main/kegiatan.html", response)

def buku(request):
    return render(request, 'main/buku.html')

def initial(request):
    words = ['universitas', 'indonesia', 'ui', 'fakultas', 'ilmu', 'komputer']
    chosen_word = random.choice(words)
    url = "https://www.googleapis.com/books/v1/volumes?q=" + chosen_word
    json_data = requests.get(url).json()
    return JsonResponse(json_data, safe=False)

def data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    json_data = requests.get(url).json()
    return JsonResponse(json_data, safe=False)

def logIn(request):
    if request.method == "POST":
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect('/buku/')
        # Redirect to a success page.
        else:
            return redirect('/login/')
        # Return an 'invalid login' error message.
        # login(request, user)
        # return redirect('/buku/')
    else: 
        return render(request, "main/login.html")

def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('/buku/')
    context = {
        'form' : form,
    }
    return render(request, "main/signup.html", context)

def logOut(request):
    logout(request)
    return redirect("/buku/")

main/templates/main/biodata.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Biodata</title>
{% endblock meta %}

{% block this%}
{% endblock this%}

{% block content %}

    <div class="foto_square"></div>
    <p id="deskripsi_singkat">Nama Lengkap: Pewe <br>
    Nama Panggilan: Pewe <br>
    Jenis Kelamin: <br>
    Tempat, Tanggal Lahir: <br>
    Alamat: <br>
    Kode Pos: <br>
        
        Email: <br>
        No. Telpon: <br>
    </p>

{% endblock content %}

main/templates/main/buku.html
<html>

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Buku</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
              <li><a href="/signup/">Sign Up</a></li>
              <li class="active"><a href="/login/">Log In <span class="sr-only">(current)</span></a></li>
              {% else %}
              <li><a href="../navbar-static-top/">Heyo {{request.user.username}}</a></li>
              <li class="active"><a href="/logout/">Log Out <span class="sr-only">(current)</span></a></li>
              {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
 
      <div class="container" style="padding-top: 100px;">
<input id="search" placeholder="Masukkan pencarian buku">
<br>
<br>
<table border="1px">
    <thead>
        <tr>
            <th>No</th>
            <th>Judul</th>
        </tr>
    </thead>
    <tbody id="hasil">

    </tbody>
</table>
      </div>
<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            url: "/initial/",
            success: function (data) {
                var array_items = data.items;
                for (i = 0; i < array_items.length; i++) {
                    $("#hasil").append("<tr><td>" + (i + 1) + "</td>" + "<td>" + array_items[i].volumeInfo.title + "</td></tr>")
                }
            }
        })
    });
    $("#search").keyup(function (item) {
        var ketikan = $("#search").val();
        //panggil ajax
        $.ajax({
            url: "/data?q=" + ketikan,
            success: function (data) {
                $("#hasil").empty();
                var array_items = data.items;
                for (i = 0; i < array_items.length; i++) {
                    $("#hasil").append("<tr><td>" + (i + 1) + "</td>" + "<td>" + array_items[i].volumeInfo.title + "</td></tr>")
                }
            }
        })
    })
</script>
</body>
</html>

main/templates/main/delete_matkul.html
<form method="POST"> {% csrf_token %}
    <h1>Apakah kamu yakin ingin menghapus matkul ini?</h1>
    <p><input type="submit" value="Ya" /> <a href="../">Tidak</a></p>
</form>

main/templates/main/detail_matkul.html
<p> {{ matkul.nama}} </p>
<p> {{ matkul.dosen}} </p>
<p> {{ matkul.sks}} </p>
<p> {{ matkul.deskripsi}} </p>
<p> {{ matkul.semester_tahun}} </p>
<p> {{ matkul.ruang_kelas}} </p>
<p><a href="/detail_matkul/{{ matkul.id}}/delete/">Delete</a></p>

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Profile</title>
<!-- <script type="text/javascript">
    alert("wey");
    function hello(){
        alert("hello");
        alert("it's me");
    }

    hello();
</script> -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

{% endblock meta %}


{% block content %}
<section>
    <div class="d-flex flex-column" id="tentang_saya">
        <div class="p-2">
            <a name="TentangSaya">
                <p id="tentang_saya_teks">Tentang Saya</p>

                <div class="foto_square"></div>
                <p id="deskripsi_singkat">Namaku Pewe, <br><br>
                    Aku aktif, ceria, dan energetik</p>
                <a href="biodata.html" id="biodata_button" class="btn btn-primary" role="button">Biodata</a>
                <a href="#Kontak" id="kontak_button" class="btn btn-secondary" role="button">Kontak</a>
            </a>
        </div>
        <div id="accordion">
            <div class="judul_accordion" id="aktivitas_judul">
                Aktivitas
                <div class="move">
                    <button class="naik">Naik</button>
                    <button class="turun">Turun</button>
                </div>
            </div>
            <div class="judul_accordion" id="aktivitas_desc">
                <p>
                    Ibadah, kuliah, organisasi, kepanitiaan
                </p>
            </div>
            <div class="judul_accordion" id="organisasi_judul">
                Pengalama Organisasi
                <div class="move">
                    <button class="naik">Naik</button>
                    <button class="turun">Turun</button>
                </div>
            </div>
            <div class="judul_accordion" id="organisasi_desc">
                <ul>
                    <li>Anggota Seksi Agama OSIS SMPN 19 Jakarta Periode 2013/2014</li>
                    <li>Ketua Seksi Agama OSIS SMPN 19 Jakarta Periode 2014/2015</li>
                    <li>Wakil Ketua Seksi VI MPK/OSIS SMAN 28 Jakarta Periode 2016/2017</li>
                    <li>Wakil Ketua OSIS MPK/OSIS SMAN 28 Jakarta Peiode 2017/2018</li>
                </ul>
            </div>
            <div class="judul_accordion" id="kepanitiaan_judul">
                Pengalaman Kepanitiaan
                <div class="move">
                    <button class="naik">Naik</button>
                    <button class="turun">Turun</button>
                </div>
            </div>
            <div class="desc_accordion">
                <p>
                    Staf Humas OH Fasilkom UI 2019 <br>
                    Staf Acara Wisuda Ganjul Fasilkom UI 2019 <br>
                    Ketua I Thalassic 2018
                </p>
            </div>
            <div class="judul_accordion" id="kepanitiaan_judul">
                Prestasi
                <div class="move">
                    <button class="naik">Naik</button>
                    <button class="turun">Turun</button>
                </div>
            </div>
            <div class="desc_accordion">
                <ul>
                    <li>juara 1</li>
                    <li>juara 2</li>
                    <li>juara 3</li>
                </ul>
            </div>
        </div>
    </div>

    <div id="sepak_terjang">
        <a name="SepakTerjang">
            <p id="sepak_terjang_teks"><a name="SepakTerjang">Sepak Terjang</a></p>
            <p id="riwayat_pendidikan">Riwayat Pendidikan</p>
            <div id="line1"></div>
            <div id="line2"></div>
            <div id="line3"></div>
            <div id="line4"></div>
            <div id="line5"></div>
            <p id="magang_kerja">Pengalaman Magang dan Kerja</p>
            <div id="line6"></div>
            <div id="line7"></div>
            <div id="line8"></div>
            <div id="line9"></div>
            <div id="line10"></div>
        </a>
    </div>
    <div id="kreasi_minat">
        <a name="KreasiMinat">
            <p id="kreasi_minat_teks">Kreasi dan Minat</p>
            <p id="kemampuan">Kemampuan</p>
            <div id="square1" class="square"></div>
            <div id="square2" class="square"></div>
            <div id="square3" class="square"></div>
            <p id="organisasi_kepanitiaan">Pengalaman Organisasi dan Kepanitiaan</p>
            <div id="square4" class="square"></div>
            <div id="square5" class="square"></div>
            <div id="square6" class="square"></div>
            <p id="hobi">Hobi</p>
            <div id="square7" class="square"></div>
            <div id="square8" class="square"></div>
            <div id="square9" class="square"></div>
            <p id="karya_proyek">Karya dan Proyek</p>
            <div id="square10" class="square"></div>
            <div id="square11" class="square"></div>
            <div id="square12" class="square"></div>
        </a>
    </div>
</section>
<footer>

    <p id="kontak"><a name="Kontak">Kontak</a></p>
    <img src="static/img/ig.png" id="ig" class="sosmed">
    <img src="static/img/whatsapp.jpg" id="wa" class="sosmed">
    <img src="static/img/facebook.png" id="fb" class="sosmed">
    <img src="static/img/linkedin.jpg" id="in" class="sosmed">

</footer>
<script src="/static/js/script.js"></script>
{% endblock content %}

main/templates/main/kegiatan.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

main/templates/main/list_matkul.html
<ol>
    {% for matkul in matkuls %}
        <li> <a href="{{ matkul.get_absolute_url }}">{{ matkul.nama }}</a> </li>
{% endfor %}
</ol>

<a href="/matkul/">Tambah Mata Kuliah</a>

main/templates/main/login.html
<form method="POST"> {% csrf_token %}
    <label for="fname">username:</label>
  <input type="text" id="fname" name="username"><br>
  <label for="lname">password:</label>
  <input type="text" id="lname" name="password"><br><br>
  <input type="submit" value="Log In">
</form>

main/templates/main/matkul.html
<!-- {% extends 'base.html' %} -->
<!-- {% load static %} -->

<!-- {% block meta %} -->
<title>Mata Kuliah</title>
<!-- {% endblock meta %} -->

<!-- {% block header %}
{% endblock header %} -->

<!-- {% block content %} -->

    <form method="POST"> {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value="Save" />
    </form>
<!-- <div id='forms'> -->
    <p><a href="/detail_matkul/">Detail Mata Kuliah</a></p>
<!-- </div> -->
<!-- {% endblock content %} -->

main/templates/main/ori.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Ori</title>
{% endblock meta %}

{% block header %}
{% endblock header %}

{% block content %}
<body>
    <div id="ori">
    <h1>Ini profilku, mana profilmu?</h1>
    <table>
        <tr>
            <td>Nama</td>
            <td>Ahmad Harori Zaki Ichsan</td>
        </tr>

        <tr>
            <td>NPM</td>
            <td>1906353965</td>
        </tr>

        <tr>
            <td>Angkatan</td>
            <td>2019</td>
        </tr>

        <tr>
            <td>Deskripsi</td>
            <td>Saya adalah seorang penuntut ilmu</td>
        </tr>

        <tr>
            <td>Tempat Kuliah</td>
            <td>Universitas Indonesia</td>
        </tr>
    </table>
    <img src="static/img/TH03.jpg" alt="Harori">
    <h3>Riwayat Pendidikan</h3>
    <table border="1">
        <thead>
            <tr>
                <th>Tahun</th>
                <th>Institusi Pendidikan</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>2005 - 2007</td>
                <td>TK Darul Ma'arif</td>
            </tr>

            <tr>
                <td>2007 - 2013</td>
                <td>SD Cenderawasih II</td>
            </tr>

            <tr>
                <td>2013 - 2016</td>
                <td>SMPN 19 Jakarta</td>
            </tr>

            <tr>
                <td>2016 - 2019</td>
                <td>SMAN 28 Jakarta</td>
            </tr>
        </tbody>
    </table>
    <a href="https://www.instagram.com/ahmadharori">
        <img src="static/img/ig.png" alt="ig Ori">
    </a>
    </div>
</body>
{% endblock content %}

main/templates/main/signup.html
<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value="Save" />
</form>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block meta %}
  <title>Profile</title>
  {% endblock meta %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/css/style.css">
</head>

<body>
  {% block header %}
  <header>
    {% block this%}
    <p id="namaku">Namaku</p>
    <p id="pewe">Pewe</p>
    <p id="web_programmer">Web Programmer</p>
    <div id="foto_oval"></div>
    {% endblock this%}
  </header>
  {% endblock header %}

  <div id="navbar">
    <h2>Pewe</h2>
    <li id="nav_tentang_saya" class="nav"><a href="{% url 'main:home'%}">Home</a></li>
    <li id="nav_sepak_terjang" class="nav"><a href="{% url 'main:biodata'%}">Biodata</a></li>
    <li id="nav_kreasi_minat" class="nav"><a href="{% url 'main:ori'%}">Ori</a></li>
    <li id="nav_kontak" class="nav"><a href="{% url 'main:matkul' %}">Mata Kuliah</a></li>
  </div>

  {% block content %}
  {% endblock content %}

  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>